spring:
  application:
    name: sv-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #路由信息
      routes:
        - id: sv-common
          uri: lb://sv-common
          predicates:
            - Path=/api/**
#        - id: sv-******
#            uri: lb://sv-******
#            predicates:
#              - Path=/api/**
  profiles:
    active: dev

server:
  port: 9876