spring:
  application:
    name: sv-common
  cloud:
    nacos:
#      discovery:
#        namespace: 4f10edd1-35a6-4ade-9da8-3048bea90201
      config:
        server-addr: 127.0.0.1:8848
#          file-extension: yaml
#          extension-configs:
#            - data-id: stardew-valley-${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.28.6.68:3306/stardew_valley?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  profiles:
    active: dev

server:
  port: 8319
  servlet:
    context-path: /api